site_name: MMM Platform Docs
site_description: Marketing Mix Modeling Platform – Developer Documentation
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Services:
      - Database: services/db.md
      - Data Science: services/ds.md
      - Backend API: services/back.md
      - Frontend: services/front.md
      - Orchestration: services/orch.md
  - How to Run: how-to-run.md
